CREATE VIEW PRODUITCATEGORIE AS
SELECT P.*,
	C.NOMCATEGORIE
FROM PRODUIT P
JOIN CATEGORIE C
ON P.IDCATEGORIE = C.IDCATEGORIE

CREATE VIEW PRODUITCOMPOSANT AS
SELECT P.*,
	C.NOMCOMPOSANT
FROM PRODUITCATEGORIE P
JOIN COMPOSITION COM
ON P.IDPRODUIT = COM.IDPRODUIT
JOIN COMPOSANT C
ON COM.IDCOMPOSANT = C.IDCOMPOSANT
