CREATE VIEW PRODUITCATEGORIE AS
SELECT P.*,
	C.NOMCATEGORIE
FROM PRODUIT P
JOIN CATEGORIE C
ON P.IDCATEGORIE = C.IDCATEGORIE

CREATE VIEW PRODUITCOMPOSANT AS
SELECT P.*,
	C.NOMCOMPOSANT
FROM PRODUITCATEGORIE P
JOIN COMPOSITION COM
ON P.IDPRODUIT = COM.IDPRODUIT
JOIN COMPOSANT C
ON COM.IDCOMPOSANT = C.IDCOMPOSANT

CREATE VIEW PRODUITVIEW AS
SELECT P.*,
	C.IDCATEGORIE,C.NOMCATEGORIE,
	U.IDUTILISATEUR,CONCAT(U.NOMUTILISATEUR,CONCAT(' ',U.PRENOM)) AS NOMCREATEUR
FROM PRODUIT P
JOIN CATEGORIE C
ON P.IDCATEGORIE = C.IDCATEGORIE
JOIN UTILISATEUR U
ON P.IDUTILISATEUR = U.IDUTILISATEUR