/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-05-12 12:28:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.*;
import s6.ReceipeFood.modele.*;
import s6.ReceipeFood.service.*;
import java.util.List;
import org.json.*;
import java.sql.*;

public final class detailAjout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Dossier%20ANTSA/s6/Mr%20Naina/Projet_s6/ProjetReceipe/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ReceipeFood%202.0/WEB-INF/lib/struts2-core-2.5.10.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1488788942000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.10.1.jar", Long.valueOf(1488788990000L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1494578955981L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1494589690801L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("s6.ReceipeFood.modele");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("s6.ReceipeFood.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"images/apple-icon-57x57.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"images/apple-icon-60x60.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"images/apple-icon-72x72.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"images/apple-icon-76x76.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"images/apple-icon-114x114.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"images/apple-icon-120x120.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"images/apple-icon-144x144.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"images/apple-icon-152x152.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"images/apple-icon-180x180.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\"  href=\"images/android-icon-192x192.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"images/favicon-32x32.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"images/favicon-96x96.png\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"images/favicon-16x16.png\">\r\n");
      out.write("    <link rel=\"manifest\" href=\"images/manifest.json\">\r\n");
      out.write("    <link href=\"plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"images/ms-icon-144x144.png\">\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" charset=\"utf-8\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"page\" class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-offset-10 col-sm-3\">\r\n");
      out.write("\t\t\t\t<a href=\"logOut\"><span class=\"glyphicon glyphicon-log-out\"></span> Deconnexion</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"header\" class=\"row\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"accueil\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"accueil\">Accueil</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"about.html\">About</a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"selected\" class=\"primary\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"product.html\">Product</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"listeRecette\">Les recettes</a>\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul class=\"secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"singlepost.html\">Single post</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"ajoutRecette\">nouvelle recette</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>");
      out.write('\r');
      out.write('\n');

	Produit produit = (Produit)request.getAttribute("produit");

      out.write("\t\r\n");
      out.write("\t\t<div id=\"body\" class=\"contact\">\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1>Ajouter une nouvelle recette</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"body\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/check-in.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<h1>UNIT 0123 , ABC BUILDING, BUSSINESS PARK</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<div class=\"contact\">\r\n");
      out.write("\t\t\t\t\t<h1>Repartissez les différents composants</h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"ajoutRecette\" class=\"load\">Précédent</a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"featured\">\r\n");
      out.write("\t\t\t\t\t\t<h4>Nom de votre recette :</h4>\r\n");
      out.write("\t\t\t\t\t\t<h1>");
 out.println(produit.getNom()); 
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t<h4>Categorie :</h4>\r\n");
      out.write("\t\t\t\t\t\t<span>");
 out.println(produit.getCategorie().getNom()); 
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<h4>Etapes à suivre :</h4>\r\n");
      out.write("\t\t\t\t\t\t<p>");
 out.println(produit.getEtape()); 
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form action=\"saveRecette\" class=\"form-horizontal\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t      ");
 
					      	int i = 0;
					      for(Composant c : (List<Composant>)request.getAttribute("ltComposant")) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"col-sm-6\" disabled=\"disabled\" type=\"text\" value=\"");
 out.println(c.getNom()); 
      out.write("\" onblur=\"this.value=!this.value?'Name':this.value;\" onfocus=\"this.select()\" onclick=\"this.value='';\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"col-sm-2\" type=\"number\" name=\"quantite[");
 out.print(i); 
      out.write("]\" placeholder=\"quantite\" onblur=\"this.value=!this.value?'Name':this.value;\" onfocus=\"this.select()\" onclick=\"this.value='';\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"col-sm-4\" class=\"icons\" name=\"unite[");
 out.print(i); 
      out.write("]\"  required>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"gramme\">Choisissez une unite</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"gramme\">gramme</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"kilogramme\">kilogramme</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"litre\">litre</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"millilitre\">millilitre</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"piece\">piece</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"cuillere\">cuillere</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"gousse\">gousse</option>\r\n");
      out.write("\t\t\t\t\t\t\t        <option value=\"\">Aucun</option>\r\n");
      out.write("\t\t\t\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t      ");
 i++; } 
      out.write("\r\n");
      out.write("\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"Ajouter recette\" id=\"submit\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"section\">\r\n");
      out.write("\t\t\t\t\t<h1>ON AIMERAIT QUE VOUS PARTAGIEZ VOS RECETTES!</h1>\r\n");
      out.write("\t\t\t\t\t<p>If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"connect\">\r\n");
      out.write("            <a href=\"http://facebook.com\" class=\"facebook\">facebook</a>\r\n");
      out.write("            <a href=\"http://twitter.com\" class=\"twitter\">twitter</a>\r\n");
      out.write("            <a href=\"http://googleplus.com\" class=\"googleplus\">googleplus</a>\r\n");
      out.write("            <a href=\"http://pinterest.com\" class=\"pinterest\">pinterest</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&copy; 2017 Freezeedera. All Rights Reserved.<br>\r\n");
      out.write("        Rakotomananjo Antsa Herilala H24 - Promo 8 A</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mobile.css\">\r\n");
      out.write("<script src=\"js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/mobile.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
