/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-05-11 18:53:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.*;
import s6.ReceipeFood.modele.*;
import s6.ReceipeFood.service.*;
import java.util.List;
import org.json.*;
import java.sql.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("s6.ReceipeFood.modele");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("org.json");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("s6.ReceipeFood.service");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html >\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Inscription/Connexion</title>\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/normalize.css\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/login.css\">\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <div class=\"form\">\n");
      out.write("      \n");
      out.write("      <ul class=\"tab-group\">\n");
      out.write("        <li class=\"tab active\"><a href=\"#signup\">Inscription</a></li>\n");
      out.write("        <li class=\"tab\"><a href=\"#login\">Connexion</a></li>\n");
      out.write("      </ul>\n");
      out.write("      \n");
      out.write("        ");
 if(request.getAttribute("error")!=null){ 
      out.write("\n");
      out.write("\t\t\t<div class=\"alert alert-danger tab-group\">\n");
      out.write("\t\t\t  <strong>Erreur!</strong>   ");
 out.println(request.getAttribute("error")); 
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t  ");
 } 
      out.write("\n");
      out.write("      \n");
      out.write("      <div class=\"tab-content\">\n");
      out.write("        <div id=\"signup\">   \n");
      out.write("          <h1>Inscrivez-vous gratuitement</h1>\n");
      out.write("          \n");
      out.write("          <form action=\"signUp\" method=\"post\">\n");
      out.write("          \n");
      out.write("          <div class=\"top-row\">\n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("              <label>\n");
      out.write("                Nom<span class=\"req\">*</span>\n");
      out.write("              </label>\n");
      out.write("              <input name=\"user.nom\" type=\"text\" required autocomplete=\"off\" />\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("              <label>\n");
      out.write("                Prenom<span class=\"req\">*</span>\n");
      out.write("              </label>\n");
      out.write("              <input name=\"user.prenom\" type=\"text\"required autocomplete=\"off\"/>\n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("              <label>\n");
      out.write("                Date de naissance<span class=\"req\">*</span>\n");
      out.write("              </label>\n");
      out.write("              <input name=\"dateNaissance\" type=\"date\"required autocomplete=\"off\"/>\n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("               <label for=\"homme\">Homme</label>\n");
      out.write("               <input class=\"\" name=\"user.sexe\" type=\"radio\" value=\"homme\" id=\"homme\" />\n");
      out.write("          </div>          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("               <label for=\"femme\">Femme</label>\n");
      out.write("               <input class=\"\" name=\"user.sexe\" type=\"radio\" value=\"femme\" id=\"femme\" />\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Adresse email<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input name=\"user.email\" type=\"email\"required autocomplete=\"off\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Mot de passe<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input name=\"user.password\" type=\"password\"required autocomplete=\"off\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Confirmer votre mot de passe<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input name=\"user.confirmPassword\" type=\"password\"required autocomplete=\"off\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("              <label>\n");
      out.write("                Adresse<span class=\"req\">*</span>\n");
      out.write("              </label>\n");
      out.write("              <input name=\"user.adresse\" type=\"text\"required autocomplete=\"off\"/>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("              <label>\n");
      out.write("                Telephone<span class=\"req\">*</span>\n");
      out.write("              </label>\n");
      out.write("              <input name=\"user.telephone\" type=\"text\"required autocomplete=\"off\"/>\n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button type=\"submit\" class=\"button button-block\"/>Inscription</button>\n");
      out.write("          \n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"login\">   \n");
      out.write("          <h1>Connectez-vous!</h1>\n");
      out.write("          \n");
      out.write("          <form action=\"login\" method=\"post\">\n");
      out.write("          \n");
      out.write("            <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Adresse email<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input name=\"user.email\" type=\"email\"required autocomplete=\"off\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"field-wrap\">\n");
      out.write("            <label>\n");
      out.write("              Mot de passe<span class=\"req\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input name=\"user.password\" type=\"password\"required autocomplete=\"off\"/>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <button class=\"button button-block\"/>Connexion</button>\n");
      out.write("          \n");
      out.write("          </form>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("      </div><!-- tab-content -->\n");
      out.write("      \n");
      out.write("</div> <!-- /form -->\n");
      out.write("    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n");
      out.write("\n");
      out.write("        <script src=\"js/index.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
